### ISSUE TITLE
Comentarios sobre la página web de OMEOMETS

### ISSUE THREAD

**Issue by 707299** [betobetok/curso-html5-design#2]
Página de Home.
1. No se porque desde un inicio se marca el recuadro naranja desde un inicio en QUI SOMES NOUS, según yo eso era sólo cuando quieres que la gente entre ahí, o ¿eso queremos?
2. Hay que decidirlo si QUI SOMES NOUS, te va a mostrar la parte donde están Hugo y Aude, pues a esa parte se refiere y para lo demás ponemos una casita de Home, por ejemplo cuando estemos en productos llego al final y está una flechita hacia arriba que me dice que si quiero ir arriba y también el home que me lleva al principio. En este texto al final del primer párrafo falta un punto.
3. En la parte de DE NOTRE FERME À VOUS, donde está el durazno no se ve completo la hoja del durazno.
4. La parte de la hoja del girasol tiene que salir del cuadrado. Se ve comido.
5. Dice Cheli que el texto de la parte de QUI SOMES NOUS, que está en negritas se ve bien, en mi browser se ve todo separado, y eso que ya lo actualizé. :( no se porqué se vea así.
6. La parte de hasta abajo donde va el contacto la siento muy grande. Yo la dejaría 3/4. Esto claro en todos los casos.
7. La interfaz de PRODUCTOS la tengo que hacer de nuevo para enviártela, en illustrator.
8. La interfaz de TRANSHUMANCIA, lo mismo yo veo el texto muy separado, abierto. Cheli dice que no.
9. Recortar aproximadamente 1cm del café obscuro de la parte de abajo y centrar la cabeza de la oveja respecto a la mancha café obscuro.
10. Crecer la foto de los becerritos hacia la izquierda, de tal modo que se alineé con el margen, es decir a donde comienza el texto que está en la mancha café. Ya que esté esto centrar la foto hacia arriba y hacia abajo.

Espero me hayas entendido.
@betobetok 

Ciaos!

**Comment by betobetok** [comment]
Hola Edne, este es el Github del curso de Html, estos comentarios los copio y los paso al github de omeomets, de cualquier forma, son varios puntos los que estan aqui, no es un solo Issue si no varios, lo copio a Ome y lo cierro para a#habrir los distintos issues que mencionas
